apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-app
  labels:
    app: lab-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab-app
  template:
    metadata:
      labels:
        app: lab-app
    spec:
      imagePullSecrets:
        - name: dockerhub-creds
      containers:
        - name: lab-app
          image: docker.io/satya66655/lab-app:v1
          ports:
            - containerPort: 8080
          # Optional health probes (uncomment if your app can respond on /)
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 8080
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 8080
          #   initialDelaySeconds: 5
          #   periodSeconds: 5

